# add our package as a plugin bundle:
plugins:
    bundles:
        twitter:
            # the name of the packages that contains plugins:
            - twitter_tutorial

# define a twitter account
twitter:
    my_account:
        auth:
            username: USERNAME
            password: PASSWORD

# use the startup event to run the "startup" pipeline once
system-events:
    startup:
        tutorial: startup

pipelines:
    startup:
        # find our current rate limitations
        - eval-lambda:
            dependencies:
                # depend on the twitter api instance:
                api: twitter.my_account
            output_path: rate_limit_status
            lambda: "_: self.dependencies.api.rate_limit_status()"

        # print the screen name:
        - pretty-print:
            path: rate_limit_status
            formatter: "status: 'Current rate limit status: %r'%status"

        - shutdown
