# we define our perspective broker server under pb.servers like this:
pb:
    servers:
        # we name our server "tutorial"
        tutorial:
            # tell it to listen for incoming tcp connections on port 8789
            listen: tcp:8789
            # all messages should be handled by the pb-server pipeline
            pipeline: pb-server


pipelines:
    pb-server:
        - passthrough