web:
    # create our web site, called "tutorial":
    tutorial:
        routing:
            __config__:
                # use the hello pipeline to render the requests to this resource
                pipeline: hello

plugins:
    bundles:
        my_bundle:
            - tutorial_bundle

pipelines:
    hello:
        - set-value:
            path: content
            value: Hello from a pipeline.

        - uppercase:
            input_path: content

        - write-web-response