web:
    site:
        routing:
            dependencies:
                __config__:
                    processor: pipeline.web.dependencies
            pipelines:
                __config__:
                    processor: pipeline.web.pipelines
            
    
pipelines:
    web:
        dependencies:
            - diagram-dependencies
            - render-dot:
                output_path: content
                type: svg
            - write-web-response:
                content_type: image/svg+xml

        pipelines:
            - diagram-pipelines
            - render-dot:
                output_path: content
                type: svg
            - write-web-response:
                content_type: image/svg+xml