includes:
    - twitter.yaml

system-events:
    startup:
        test: pipeline.system-testing

pipelines:
    system-testing:
        - create-statustest-reporter
        - test-twitter
        - wait-for-statustest-reporter:
            done: true
        - shutdown